### ISSUE TITLE
Container attribute for serializating structs as tuple structs

### ISSUE THREAD

**Issue by jethrogb** [serde-rs/serde#1648] opened 2019-10-14 13:08 UTC
The default deserializer can already deserialize tuple structs as regular structs (with the Seq visitor). However, if you want to serialize a struct as a tuple struct (without field names), you have to manually implement `Serialize`. It would be nice to have this option as a container attribute.

**Comment by jean-airoldie** [comment] 2020-01-07 17:31
Check out https://crates.io/crates/serde_tuple.

**Comment by birkenfeld** [comment] 2020-06-20 07:07
I second this request; if it should stay in the external crate a reference from the serde docs would be nice.

**Comment by chloekek** [comment] 2023-04-02 00:27
This is a duplicate of #297.

**Comment by dtolnay** [comment] 2023-07-09 22:39
Between `serde_tuple` and the possibility of handwriting a pretty straightforward `Serialize` impl, I think this use case is served well enough that I wouldn't want to build something dedicated for this into serde_derive.

**Closed by dtolnay** 2023-07-09 22:39 UTC
