### ISSUE TITLE
with a dependency on serde_macros, 'index out of bounds: the len is 92 but the index is 529

### ISSUE THREAD

**Issue by evadnoob** [serde-rs/serde#97] opened 2015-07-02 02:06 UTC
When I add serde_macros = "0.4.1" to Cargo.toml, I get the error below:

I'm using rust nightly: ```rustc 1.3.0-nightly (bf3c979ec 2015-06-30)```

```

RUST_BACKTRACE=1 cargo build
error: internal compiler error: unexpected panic
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
Could not compile `serde_codegen`.

   Compiling serde_codegen v0.4.2
error: internal compiler error: unexpected panic
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
thread 'rustc' panicked at 'index out of bounds: the len is 92 but the index is 529', ../src/libcollections/vec.rs:1362

stack backtrace:
   1:        0x104c67485 - sys::backtrace::write::ha69861d01c280e10Vns
   2:        0x104c6fbe3 - panicking::on_panic::he1db6e7d5ec9c9022Fw
   3:        0x104c2baf2 - rt::unwind::begin_unwind_inner::h9f73b873795fcd2deow
   4:        0x104c2c849 - rt::unwind::begin_unwind_fmt::h3999b4670fb43708knw
   5:        0x104c6f76c - rust_begin_unwind
   6:        0x104cc3e35 - panicking::panic_fmt::he89ea3094b3178e919B
   7:        0x104cbe5b5 - panicking::panic_bounds_check::h8058af339f14343278B
   8:        0x109f75347 - util::interner::StrInterner::get::h33e23c9881d31a76Fpa
   9:        0x10655c224 - parse::token::get_name::hc8e6f23ae3b0497cwaT
  10:        0x10655c398 - parse::token::get_ident::h623c49ac14f4e12cNaT
  11:        0x10655c34c - str::ast..Ident.ToInternedString::to_interned_string::h226749af2201972apgd
  12:        0x1065074b4 - lit::LitBuilder<F>::str::h4609815677029230994
  13:        0x1065073f5 - expr::ExprBuilder<F>::str::h6929319462409805750
  14:        0x106507143 - mk_ident::h76e644649ecee0d6Yia
  15:        0x10650fdb7 - expr_mk_token::h530e0aaf1ac4f9c2Cla
  16:        0x106514578 - statements_mk_tt::ha8ed870f505b201bBAa
  17:        0x10651cf8e - statements_mk_tt::closure.5782
  18:        0x10651cf1d - iter::FlatMap<I, U, F>.Iterator::next::closure.5777
  19:        0x10651ce7d - option::Option<T>::map::h16995687183900979700
  20:        0x10651cc0d - iter::FlatMap<I, U, F>.Iterator::next::h11672890417399050160
  21:        0x10651c9bd - iter::Chain<A, B>.Iterator::next::h435140630083791431
  22:        0x10651c8a1 - iter::Chain<A, B>.Iterator::next::h15770457910323705126
  23:        0x10651df34 - vec::Vec<T>::extend_desugared::h7871689067938150292
  24:        0x10651c561 - vec::Vec<T>.FromIterator<T>::from_iter::h12946602305841387152
  25:        0x10651c0db - iter::Iterator::collect::h2775758658509774241
  26:        0x10651549f - statements_mk_tt::ha8ed870f505b201bBAa
  27:        0x10650171d - statements_mk_tts::hf5a22e049c2a847cZJa
  28:        0x1064e38c2 - expand_tts::h4a76f356700220c2QKa
  29:        0x1064fcacb - expand_parse_call::h847fdc0375aa33afHMa
  30:        0x1064fdc23 - expand_quote_expr::hb1131b5a4ef58447Oba
  31:        0x1099f4bbe - ext::base::F.TTMacroExpander::expand::h16772666232880655435
  32:        0x1026efe8b - ext::expand::expand_expr::closure.64675
  33:        0x1026eb510 - ext::expand::expand_expr::h99495f0a4050bb0eO3a
  34:        0x1027447de - ext::expand::expand_block_elts::closure.65395
  35:        0x102742b3e - ext::expand::expand_block_elts::closure.65376
  36:        0x1026feb8a - ext::expand::expand_block_elts::hae5d90e0cb6f3badrPb
  37:        0x102742552 - ext::expand::expand_block::h19a07d5850d44ec3MOb
  38:        0x1026f4b93 - fold::noop_fold_expr::h13944231768787436517
  39:        0x1026eb712 - ext::expand::expand_expr::closure.64675
  40:        0x1026eb510 - ext::expand::expand_expr::h99495f0a4050bb0eO3a
  41:        0x10273e130 - ext::expand::expand_arm::h362881c67b77a2bf5Jb
  42:        0x1026f47d7 - fold::noop_fold_expr::h13944231768787436517
  43:        0x1026eb712 - ext::expand::expand_expr::closure.64675
  44:        0x1026eb510 - ext::expand::expand_expr::h99495f0a4050bb0eO3a
  45:        0x1027447de - ext::expand::expand_block_elts::closure.65395
  46:        0x102742b3e - ext::expand::expand_block_elts::closure.65376
  47:        0x1026feb8a - ext::expand::expand_block_elts::hae5d90e0cb6f3badrPb
  48:        0x102742552 - ext::expand::expand_block::h19a07d5850d44ec3MOb
  49:        0x1026fe55c - ext::expand::expand_and_rename_fn_decl_and_block::h2f6d7bbfc095110aQic
  50:        0x10276a677 - ext::expand::expand_and_rename_method::h146aa2e4f3025329akc
  51:        0x10276f63d - ext::expand::expand_impl_item::closure.65794
  52:        0x10276bf05 - ext::expand::expand_impl_item::h624cadcd858560f3zfc
  53:        0x1027022ea - ext::expand::expand_annotatable::hd1384fdfcaa7365bNZb
  54:        0x10271191f - ext::expand::MacroExpander<'a, 'b>.Folder::fold_impl_item::h3c6c8bcc8f2aea45Gnc
  55:        0x10271139c - iter::FlatMap<I, U, F>.Iterator::next::h2176610863638934878
  56:        0x1027116c6 - vec::Vec<T>::extend_desugared::h3745718402942750841
  57:        0x1027103d7 - iter::Iterator::collect::h15651229304304986698
  58:        0x102706e93 - ext::expand::expand_item_underscore::hc68401b64125c559Vsb
  59:        0x102769744 - fold::Folder::fold_item_simple::h6115586095879100014
  60:        0x102769313 - ptr::P<T>::map::h8648109792104747851
  61:        0x102702fcd - ext::expand::expand_annotatable::hd1384fdfcaa7365bNZb
  62:        0x1026fed11 - ext::expand::expand_item::h544d5c924b5556adksb
  63:        0x10270bc0a - iter::FlatMap<I, U, F>.Iterator::next::h10402144123647243192
  64:        0x10270ab17 - vec::Vec<T>.FromIterator<T>::from_iter::h2531848258214199605
  65:        0x10270a2df - fold::noop_fold_mod::h11533148739362704925
  66:        0x10270628e - ext::expand::expand_item_underscore::hc68401b64125c559Vsb
  67:        0x102769744 - fold::Folder::fold_item_simple::h6115586095879100014
  68:        0x102769313 - ptr::P<T>::map::h8648109792104747851
  69:        0x102703a4d - ext::expand::expand_annotatable::hd1384fdfcaa7365bNZb
  70:        0x1026fed11 - ext::expand::expand_item::h544d5c924b5556adksb
  71:        0x1027172e4 - iter::FlatMap<I, U, F>.Iterator::next::h4604195285113091658
  72:        0x102716357 - util::small_vector::SmallVector<T>.FromIterator<T>::from_iter::h15534074357520757775
  73:        0x1027151fb - ext::expand::expand_item_mac::h42d76a4eac0c1d4bmvb
  74:        0x1027029d7 - ext::expand::expand_annotatable::hd1384fdfcaa7365bNZb
  75:        0x1026fed11 - ext::expand::expand_item::h544d5c924b5556adksb
  76:        0x10270bc0a - iter::FlatMap<I, U, F>.Iterator::next::h10402144123647243192
  77:        0x10270ab17 - vec::Vec<T>.FromIterator<T>::from_iter::h2531848258214199605
  78:        0x10270a2df - fold::noop_fold_mod::h11533148739362704925
  79:        0x10270628e - ext::expand::expand_item_underscore::hc68401b64125c559Vsb
  80:        0x102769744 - fold::Folder::fold_item_simple::h6115586095879100014
  81:        0x102769313 - ptr::P<T>::map::h8648109792104747851
  82:        0x102703a4d - ext::expand::expand_annotatable::hd1384fdfcaa7365bNZb
  83:        0x1026fed11 - ext::expand::expand_item::h544d5c924b5556adksb
  84:        0x1027729ef - ext::expand::expand_crate::he8ff7220990af98elrc
  85:        0x101144aa2 - driver::phase_2_configure_and_expand::closure.21445
  86:        0x1010f9bd2 - driver::phase_2_configure_and_expand::h154d7c2f9d5ff029ita
  87:        0x1010e944d - driver::compile_input::hb76410fc800a2a41Tba
  88:        0x1011c33af - run_compiler::hd724b5fef3441688y7b
  89:        0x1011c0c63 - boxed::F.FnBox<A>::call_box::h16633087113713113418
  90:        0x1011c0427 - rt::unwind::try::try_fn::h14742554275296927735
  91:        0x104cfc0f8 - rust_try_inner
  92:        0x104cfc0e5 - rust_try
  93:        0x104c599a5 - rt::unwind::try::inner_try::h2041d75ee62fcacd7jw
  94:        0x1011c0658 - boxed::F.FnBox<A>::call_box::h11995599304104652074
  95:        0x104c6e66d - sys::thread::Thread::new::thread_start::hb06fec4578e7b89frIv
  96:     0x7fff95ccd2fb - _pthread_body
  97:     0x7fff95ccd278 - _pthread_start

Could not compile `serde_codegen`.

To learn more, run the command again with --verbose.

```

**Comment by erickt** [comment] 2015-07-02 02:12
That's not good. Do you have your code online that we can check it out?

**Comment by evadnoob** [comment] 2015-07-02 11:45
I do.  https://github.com/evadnoob/rustoleum/tree/with-serde

That branch, ```cargo build``` should show the error

**Comment by oli-obk** [comment] 2015-08-04 11:14
can't reproduce on 0.4.3:

```
src/jobs.rs:12:20: 12:34 error: the trait `serde::de::Deserialize` is not implemented for the type `storage::Job` [E0277]
src/jobs.rs:12     let job: Job = json::from_str(raw_json).unwrap();
                                  ^~~~~~~~~~~~~~
src/jobs.rs:12:20: 12:34 help: run `rustc --explain E0277` to see a detailed explanation
src/storage.rs:234:27: 234:49 error: the trait `serde::ser::Serialize` is not implemented for the type `storage::Job` [E0277]
src/storage.rs:234         let job_as_json = json::to_string_pretty(&job).unwrap();
                                             ^~~~~~~~~~~~~~~~~~~~~~
src/storage.rs:234:27: 234:49 help: run `rustc --explain E0277` to see a detailed explanation
error: aborting due to 2 previous errors
Could not compile `bldr`.
```

**Comment by dtolnay** [comment] 2016-05-13 18:43
Closing this as an ancient compiler bug that seems to have been fixed. We can investigate further if anyone sees this again.

**Closed by dtolnay** 2016-05-13 18:43 UTC
