### ISSUE TITLE
Aliases for enum variants are not working with flattened enums

### ISSUE THREAD

**Issue by Bergmann89** [serde-rs/serde#1847] opened 2020-07-02 09:03 UTC
I have an enum with some aliases for the variants. The enum is placed as field inside a struct. If I add the `flatten` tag to the field, the deserialization fails with the error `no variant of enum MyEnum found in flattened data`. If I don't use the flatten tag, everything works as expected.  

Not working example (with flatten tag):
```rust
#[derive(Deserialize, Debug, PartialEq)]
pub enum MyEnum {
    #[serde(alias = "ValueStringAlias")]
    #[serde(rename = "ValueString")]
    String(String),

    #[serde(alias = "ValueBooleanAlias")]
    #[serde(rename = "ValueBoolean")]
    Boolean(bool),
}

#[derive(Deserialize, Debug, PartialEq)]
#[serde(rename_all = "PascalCase")]
struct Test {
    number: u32,

    #[serde(flatten)]
    my_enum: MyEnum,
};

const TEST_XML: &'static str = r##"
    <Test>
        <Number>123</Number>
        <ValueBooleanAlias>true</ValueBooleanAlias>
    </Test>
"##;
```

Working example (without flatten tag):
```rust
#[derive(Deserialize, Debug, PartialEq)]
pub enum MyEnum {
    #[serde(alias = "ValueStringAlias")]
    #[serde(rename = "ValueString")]
    String(String),

    #[serde(alias = "ValueBooleanAlias")]
    #[serde(rename = "ValueBoolean")]
    Boolean(bool),
}

#[derive(Deserialize, Debug, PartialEq)]
#[serde(rename_all = "PascalCase")]
struct Test {
    number: u32,
    my_enum: MyEnum,
};

const TEST_XML: &'static str = r##"
    <Test>
        <Number>123</Number>
        <MyEnum>
            <ValueBooleanAlias>true</ValueBooleanAlias>
        </MyEnum>
    </Test>
"##;
```

I've used quick-xml as deserializer here, but it semse to be a bug of serde.

**Comment by dtolnay** [comment] 2022-01-23 05:08
Closing as a duplicate of #1504.

**Closed by dtolnay** 2022-01-23 05:08 UTC

**Comment by Anders429** [comment] 2024-07-28 22:18
While the duplicate issue, #1504, is closed, the issue in the original comment here is still a problem. Using the same code from the original comment, I have put together an example using `serde_json` (so I could have it run on the playground) to show the problem: https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=088644732feb07e0e7d1a97f423838ad

It seems that the solution to #1504 fixed the problem for *field* aliases, but not *variant* aliases.

Can we reopen this issue? Or is there another issue tracking enum variant aliases?

**Comment by Mingun** [comment] 2024-07-29 05:39
Probably, #2566 will fix that, the relevant lines seems to the here:
https://github.com/serde-rs/serde/pull/2566/files#diff-2a062279ae10fa8cfea059371a1320afc87b998e7153017941e31ff7450ca64aR1218-R1221

**Comment by jaymell** [comment] 2024-08-14 22:20
@Anders429 You have a nice repro for the outstanding problem with enum variants. I would open a separate issue for better tracking.

**Comment by kskalski** [comment] 2024-10-23 00:21
Seems like the outstanding problem with enum+alias+flattened is also reported here https://github.com/serde-rs/serde/issues/2188

**Comment by Anders429** [comment] 2024-12-06 16:00
#2566 does completely resolve this issue. This can be verified by rerunning the playground I linked above.
