### ISSUE TITLE
Please, add support for `[u8; 42]`

### ISSUE THREAD

**Issue by YellingOilbird** [serde-rs/serde#2419] opened 2023-03-26 00:00 UTC
That flow needs to implement fixed array for many things with ethereum address. For example, for retrieving from a database fixed strings with that size. Now I use custom serde for this (deserialisation is not available). Slice (&[u8]) grabs more bytes to fit 48 bytes length.

**Comment by dtolnay** [comment] 2023-03-26 02:04
Closing as a duplicate of #631.

**Closed by dtolnay** 2023-03-26 02:04 UTC
