### ISSUE TITLE
Skipped fields still error as unknown

### ISSUE THREAD

**Issue by Mark-Simulacrum** [serde-rs/serde#1164] opened 2018-02-25 02:27 UTC
As https://play.rust-lang.org/?gist=d32b5f2e2f37bd6c8c87e403f2a26f6e&version=stable illustrates, I would expect when deserializing a structure with skipped fields, `deny_unknown_fields` does not error on them.

I'd be okay with some *other* annotation here -- maybe `#[serde(default, skip)]` on the field explicitly? That seems odd though.

```rust
#[macro_use]
extern crate serde;
extern crate serde_json;

#[derive(Debug, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields, default)]
struct Skipped {
    #[serde(skip)] optional: String,
}

impl Default for Skipped {
    fn default() -> Self {
        Self {
            optional: "World".to_owned(),
        }
    }
}

fn main() {
    let _data: Skipped = serde_json::from_str("{}").unwrap();
    let _data: Skipped = serde_json::from_str(r#"{"skipped": "test"}"#).unwrap();
}
```

**Comment by dtolnay** [comment] 2018-03-03 20:36
This sounds like the reverse of #444. :laughing: 

Can you explain a bit more about your use case here? It sounds like you have a field that exists in your JSON input **and** that you want to have in your Rust struct, but that when deserializing you want the field in the Rust struct to hold its default value rather than the value from the input?

If I got it right, a `deserialize_with` function may be better suited. It would ignore the field value in the input by deserializing to [`IgnoredAny`](https://docs.serde.rs/serde/de/struct.IgnoredAny.html), then produce a default value to put in the struct.

```rust
#[macro_use]
extern crate serde_derive;

extern crate serde;
extern crate serde_json;

use serde::de::{Deserialize, Deserializer, IgnoredAny};

#[derive(Debug, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
struct Skipped {
    #[serde(default, deserialize_with = "skip", skip_serializing)]
    skipped: String,
}

fn skip<'de, D, T>(deserializer: D) -> Result<T, D::Error>
where
    D: Deserializer<'de>,
    T: Default,
{
    // Ignore the data in the input.
    IgnoredAny::deserialize(deserializer)?;
    Ok(T::default())
}

fn main() {
    let data: Skipped = serde_json::from_str("{}").unwrap();
    println!("empty: {:?}", data);
    let data: Skipped = serde_json::from_str(r#"{"skipped": "Hello"}"#).unwrap();
    println!("non-default: {:?}", data);
}
```

**Comment by dtolnay** [comment] 2018-03-25 10:47
Closing as intended behavior.

**Closed by dtolnay** 2018-03-25 10:47 UTC

**Comment by Mark-Simulacrum** [comment] 2018-03-25 11:14
Yes, sorry I missed your message from before; using a deserialize_with attribute seems fine. Thanks!
