### ISSUE TITLE
Deserializing a nested enum returns an error

### ISSUE THREAD

**Issue by tbraun96** [serde-rs/serde#1734] opened 2020-02-01 14:01 UTC
serde version: 1.0.104
Rust nightly 1.42.0

Ever since upgrading serde, I have been getting a strange error when serializing this structure:

```
#[derive(Serialize, Deserialize, Default)]
/// Inner device
pub struct NetworkAccountInner {
    nid: u64,
    pub(crate) global_ipv4: Option<IpAddr>,
    pub(crate) global_ipv6: Option<IpAddr>,
    local_save_path: Option<PathBuf>,
    #[serde(skip)]
    pub config_file: Option<Mutex<ConfigFile>>
}
```

During the deserialization phase, I am getting this error:

```
Err: invalid type: integer `0`, expected `V4` or `V6`
```

I figured that is likely because we have an ```Option<IpAddr>``` type; serde serializes this as "0" since it's "None" when serialized. Although, I'm not entirely sure because this isn't my project :)

Also, I've tried using bincode and several other higher-level serializers ontop of serde, but am getting the same error. The error is invariant to the use of higher-level serialization abstractions

**Comment by dtolnay** [comment] 2020-02-01 18:59
I was not able to reproduce this. Please minimize this (using only IpAddr if that is what causes the problem, leaving out everything unrelated like ConfigFile) and provide a runnable Rust program that reproduces the error message.

Here is what I tried:

```rust
use serde::{Deserialize, Serialize};
use std::net::IpAddr;
use std::path::PathBuf;

#[derive(Serialize, Deserialize, Debug)]
struct NetworkAccountInner {
    nid: u64,
    global_ipv4: Option<IpAddr>,
    global_ipv6: Option<IpAddr>,
    local_save_path: Option<PathBuf>,
}

fn main() {
    let x = NetworkAccountInner {
        nid: 0,
        global_ipv4: None, // or Some(IpAddr::V4(Ipv4Addr::LOCALHOST))
        global_ipv6: None, // or Some(IpAddr::V6(Ipv6Addr::LOCALHOST))
        local_save_path: None,
    };
    let bytes = bincode::serialize(&x).unwrap();
    let y = bincode::deserialize::<NetworkAccountInner>(&bytes).unwrap();
    println!("{:#?}", y);
}
```

**Comment by AwesomeIbex** [comment] 2020-05-05 20:25
I've had the same issue.

I'm integrating with the Slack API and I have an ADT that is a representation of the polymorphic payloads. Slack sends an object payload like below:

```
{
    "token": "Jhj5dZrVaK7ZwHHjRyZWjbDl",
    "challenge": "3eZbrw1aBm2rZgRNFdxV2595E9CY3gmdALWMmHkvFXO7tYXAYM8P",
    "type": "url_verification"
}
```

But what works is 
```
{
    "SlackHandshake": {
    	"token": "Jhj5dZrVaK7ZwHHjRyZWjbDl",
    	"challenge": "3eZbrw1aBm2rZgRNFdxV2595E9CY3gmdALWMmHkvFXO7tYXAYM8P",
    	"type": "url_verification"
    }
}
```

I'm sure there's just a missed config that would allow me to lift the object out and match on the type, just posting to provide some additional context.

Here's my ADT:
```Rust
#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub enum SlackMessage {
    SlackHandshake(SlackHandshake),
    SlackEvent(SlackEvent),
}
```

**Comment by AwesomeIbex** [comment] 2020-05-06 11:01
@tbraun96  I think there is some functionality for this: `#[serde(flatten)]` should do the trick. Although I couldn't get it to work :)

**Comment by dtolnay** [comment] 2020-05-09 22:02
I am going to close this since we still have no repro for the original issue. I am not convinced that @AwesomeIbex's situation is related.

Please file a new issue for the `Option<IpAddr>`-related error if someone is able to provide a compilable Rust program that reproduces the error.

**Closed by dtolnay** 2020-05-09 22:02 UTC
