### ISSUE TITLE
Action immediately after deserialization?

### ISSUE THREAD

**Issue by SuperFluffy** [serde-rs/serde#626] opened 2016-11-20 14:25 UTC
Can we add an attribute like `after_deserialization=<path_to_fn>`, which calls `fn` with a mutable reference to the struct (or which takes ownership of the struct)  we just deserialized? Or is that too specific?

I have a few structs which carry a temporary state with them, which I however do not serialize, and thus do not deserialize. At the same time, I cannot simply assign a default to them, since their value depends on the other fields in the struct. They look like this:

```rust
#[derive(Serialize,Deserialize)]
struct Foo<T> {
    to_serialize: usize,
    #[serde(skip_serializing,skip_deserializing,default)]
    not_to_serialize: usize,
}
```

Now, after deserialization is complete, I now have to issues calls like `Foo::init_temporaries` so that the temporary variables get set properly. For example, if `to_serialize` was a `Vec`, I might set `self.not_to_serialize = vec![0; self.to_serialize.len()]`.

**Comment by dtolnay** [comment] 2017-01-07 21:30
#642 is a duplicate of this but a bit more fleshed out so let's continue the discussion there. This is definitely something I am interested in supporting.

**Closed by dtolnay** 2017-01-07 21:30 UTC
Labels: enhancement
