### ISSUE TITLE
serde@1.0.204 breaks compiles

### ISSUE THREAD

**Issue by dignifiedquire** [serde-rs/serde#2772] opened 2024-07-07 20:02 UTC
CI on rpgp is broken since the latest release of `serde@1.0.24`

Part of the error log, I tried both `1.80` and `1.78` nightly versions

```
error[E0658]: `#[diagnostic]` attribute name space is experimental
Error:    --> /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/serde-1.0.204/src/de/mod.rs:537:5
    |
537 |     diagnostic::on_unimplemented(
    |     ^^^^^^^^^^
    |
    = note: see issue #11[199](https://github.com/rpgp/rpgp/actions/runs/9829921674/job/27135527807?pr=368#step:5:200)6 <https://github.com/rust-lang/rust/issues/111996> for more information
    = help: add `#![feature(diagnostic_namespace)]` to the crate attributes to enable
    = note: this compiler was built on [202](https://github.com/rpgp/rpgp/actions/runs/9829921674/job/27135527807?pr=368#step:5:203)4-02-06; consider upgrading it if it is out of date

error[E0658]: `#[diagnostic]` attribute name space is experimental
Error:    --> /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/serde-1.0.[204](https://github.com/rpgp/rpgp/actions/runs/9829921674/job/27135527807?pr=368#step:5:205)/src/ser/mod.rs:220:5
    |
220 |     diagnostic::on_unimplemented(
    |     ^^^^^^^^^^
    |
    = note: see issue #111996 <https://github.com/rust-lang/rust/issues/111996> for more information
    = help: add `#![feature(diagnostic_namespace)]` to the crate attributes to enable
    = note: this compiler was built on 2024-02-06; consider upgrading it if it is out of date

   Compiling wasm-bindgen-macro-support v0.2.92
For more information about this error, try `rustc --explain E0658`.
The following warnings were emitted during compilation:
```

More logs: 

https://github.com/rpgp/rpgp/actions/runs/9829921674/job/27135527807?pr=368

**Comment by dtolnay** [comment] 2024-07-07 20:06
This is a duplicate of https://github.com/serde-rs/serde/issues/2770.

**Closed by dtolnay** 2024-07-07 20:06 UTC

**Comment by dignifiedquire** [comment] 2024-07-07 20:10
What exactly do you mean with that? `rustc 1.80.0-nightly (79734f1db 2024-05-02)` is not a particularly old nightly, could you clarify what nightlies will be supported?

**Comment by oli-obk** [comment] 2024-07-08 05:57
The first nightly where this feature is stable. Either try some nightlies or just pick the one at a date of a stable release, at which point it's guaranteed to work
