### ISSUE TITLE
Attributes `alias` and `flatten` don't seem to work together (serde_json)

### ISSUE THREAD

**Issue by Ploppz** [serde-rs/serde#1976] opened 2021-02-04 16:39 UTC
At least in this example: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=c2ee5b544b5b939cf67f364d756f5bea

`serde_json::from_str` gives error
> "missing field `calculation_status`"

even though `calculationStatus` is there and we have such an alias.

If you move the `calculation_status` field with attributes directly into the `Plate` struct (and remove `PlateFlags`), it works.

**Comment by bmc-msft** [comment] 2021-04-05 15:09
I can confirm this is an issue.

Example:
```rust
use serde_derive::{Deserialize};

#[derive(Deserialize, Debug)]
pub struct Config {
    #[serde(alias = "field1")]
    pub new_name: Option<String>,

    pub field2: Option<String>,
}

#[derive(Deserialize, Debug)]
pub struct NestedConfig {
    #[serde(flatten)]
    pub common: Config,
}

fn main() {
    let raw = "{\"field1\": \"value1\", \"field2\": \"value2\"}";
    let config: Config = serde_json::from_str(&raw).unwrap();
    println!("{:?}", config);

    let nested: NestedConfig = serde_json::from_str(&raw).unwrap();
    println!("{:?}", nested);
}
```


This results in:
```
Config { new_name: Some("value1"), field2: Some("value2") }
NestedConfig { common: Config { new_name: None, field2: Some("value2") } }
```

**Comment by SciStarter** [comment] 2021-09-07 10:29
This looks like a duplicate of https://github.com/serde-rs/serde/issues/1504

**Comment by dtolnay** [comment] 2022-01-23 03:45
Closing as a duplicate of #1504.

**Closed by dtolnay** 2022-01-23 03:45 UTC
