### ISSUE TITLE
"proc-macro derive panicked" when using "cbindgen"

### ISSUE THREAD

**Issue by ralfbiedert** [serde-rs/serde#1357] opened 2018-08-16 09:32 UTC
Not sure if related to issue #1329, but compiling this produces a panic:

```rust
use serde_derive::Serialize;

#[derive(Serialize)]
crate enum E { // `crate` seems to be causing this
    X,
}

fn main() {}
```

`Cargo.toml`:

```ini
[dependencies]
serde = "^1.0"
serde_json = "^1.0"
serde_derive = "^1.0"

[dev-dependencies]
cbindgen = "0.6"
```

Error:
```
error: proc-macro derive panicked
 --> src/main.rs:3:10
  |
3 | #[derive(Serialize)]
  |          ^^^^^^^^^
  |
  = help: message: called `Result::unwrap()` on an `Err` value: "failed to parse derive input: \"crate enum E { X, }\""

error: aborting due to previous error

error: Could not compile `rust_playground`.
```

```
rustc 1.30.0-nightly (67390c0c3 2018-08-14)
```

**Comment by ralfbiedert** [comment] 2018-08-16 09:36
This seems to cause problems as well:

```rust
#[derive(Debug, Clone, Copy, Serialize)]
#[repr(C)]
pub struct Matrix4f32 {
    crate data: [f32; 16],
}
```

Error:
```
--> src/main.rs:9:30
  |
9 | #[derive(Debug, Clone, Copy, Serialize)]
  |                              ^^^^^^^^^
  |
  = help: message: called `Result::unwrap()` on an `Err` value: "failed to parse derive input: \"#[repr(C)]\\npub struct Matrix4f32 {\\n    crate data: [f32; 16],\\n}\""

error: aborting due to previous error
```

**Comment by dtolnay** [comment] 2018-08-16 16:39
It appears to work in the playground -- [link](https://play.rust-lang.org/?gist=eca791392e0d3bcaf2356869f1d5608d&version=nightly&mode=debug&edition=2018). Can you help me reproduce this?

**Comment by ralfbiedert** [comment] 2018-08-16 22:47
[Here is a repository](https://github.com/ralfbiedert/rust_issues/tree/serde-%231357) that reproduces the problem for me.

**Rustc** `1.30.0-nightly (67390c0c3 2018-08-14)`
**macOS** `10.13.6 (17G65)`

```
> cargo build
   Compiling unicode-xid v0.0.4                                                                
   Compiling quote v0.3.15
   Compiling serde v1.0.71
   Compiling ryu v0.2.3
   Compiling itoa v0.4.2
   Compiling synom v0.11.3
   Compiling syn v0.11.11
   Compiling serde_derive_internals v0.17.0
   Compiling serde_derive v1.0.21
   Compiling serde_json v1.0.26
   Compiling rust_issues v0.1.0 (file:///...)
error: proc-macro derive panicked
 --> src/main.rs:9:30
  |
9 | #[derive(Debug, Clone, Copy, Serialize)]
  |                              ^^^^^^^^^
  |
  = help: message: called `Result::unwrap()` on an `Err` value: "failed to parse derive input: \"#[repr(C)]\\npub struct Matrix4f32 {\\n    crate data: [f32; 16],\\n}\""

error: aborting due to previous error

error: Could not compile `rust_issues`.

To learn more, run the command again with --verbose.
```

**Comment by ralfbiedert** [comment] 2018-08-16 22:48
(I think the trick is you also have to import `cbindgen`)

**Comment by dtolnay** [comment] 2018-08-17 03:44
Thanks! It looks like cbindgen currently disallows using any newer version of serde_derive than one from 9 months ago (which was before `crate` visibility was supported) because their Cargo.toml contains:

```ini
serde_derive = "=1.0.21"
```

I am closing this issue because this is something you would need to sort out with the cbindgen folks. If there is anything Serde can do to unblock cbindgen in using our new releases then we can follow up about that.

**Closed by dtolnay** 2018-08-17 03:44 UTC
