### ISSUE TITLE
Serde Remote for struct with generic cannot compile

### ISSUE THREAD

**Issue by aitvann** [serde-rs/serde#1844] opened 2020-06-26 12:18 UTC
This sample code:

``` rust
use serde::Deserialize;

mod remote {
    pub struct Bar<T> {
        value: T,
    }

    impl<T> Bar<T> {
        pub fn new(value: T) -> Self {
            Self { value }
        }

        pub fn get_ref(&self) -> &T {
            &self.value
        }
    }
}

#[derive(Deserialize)]
#[serde(remote = "remote::Bar")]
struct BarDef<T> {
    #[serde(getter = "remote::Bar::get_ref")]
    value: T,
}

impl<T> From<BarDef<T>> for remote::Bar<T> {
    fn from(src: BarDef<T>) -> Self {
        remote::Bar::new(src.value)
    }
}
```

will fail with:

```
error[E0107]: wrong number of type arguments: expected 1, found 0
    --> src/main.rs:1271:18
     |
1271 | #[serde(remote = "remote::Bar")]
     |                  ^^^^^^^^^^^^^ expected 1 type argument
```

If I try to specify the type argument like `remote = "remote::Bar<T>"` or like `remote = "remote::Bar::<T>"` it still fail:

```
error: expected one of `!`, `+`, `,`, `::`, or `>`, found `<`
    --> src/main.rs:1272:14
     |
1270 | #[derive(Deserialize)]
     |          -----------
     |          |
     |          while parsing this item list starting here
     |          the item list ends here
1271 | #[serde(remote = "remote::Bar::<T>")]
     |                                    - expected one of `!`, `+`, `,`, `::`, or `>`
1272 | struct BarDef<T> {
     |              ^ unexpected token

error: proc-macro derive produced unparseable tokens
    --> src/main.rs:1270:10
     |
1270 | #[derive(Deserialize)]
     |          ^^^^^^^^^^^
```

Note then if `value` field of `remote::Bar` is public and I remove `#[serde(getter = "...")]` then it works well, but it isn't my case. Is this a bug or this functionality is not yet available?

**Comment by dtolnay** [comment] 2020-06-26 17:41
This looks like a bug. I would accept a PR to fix this.

**Comment by dtolnay** [comment] 2023-07-09 20:23
Fixed in serde_derive 1.0.148.

**Closed by dtolnay** 2023-07-09 20:23 UTC

**Comment by Mingun** [comment] 2023-07-09 20:27
@dtolnay, for clarity -- is there a regression test for that?

**Comment by dtolnay** [comment] 2023-07-09 20:40
Yes. The PR is linked from the release notes of 1.0.148.
