### ISSUE TITLE
Use mutable values in the `content` of `serde (tag="t", content="c")`

### ISSUE THREAD

**Issue by MaxKingPor** [serde-rs/serde#2826] opened 2024-09-25 08:46 UTC
I have an API whose request body looks like this:
```Json
{
    "msgtype": "text",
    "text": {
        "content": "som message"
    }
}

```

```Json
{
    "msgtype": "image",
    "image": {
        "base64": "DATA",
        "md5": "MD5"
    }
}

```

I think the 'content' should be modified

# Exp
```Rust
#[derive(Debug, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "snake_case")]
#[serde(tag = "msgtypet", content_all="snake_case")]
enum RequestsBody {
    #[serde(content="text")]
    Text {
        content: String,
        #[serde(skip_serializing_if="Option::is_none")]
        mentioned_list: Option<Vec<String>>,
        #[serde(skip_serializing_if="Option::is_none")]
        mentioned_mobile_list: Option<Vec<String>>,
    },
    Image {
        base64: String,
        md5: String,
    },
}
```

**Comment by Mingun** [comment] 2024-09-25 10:18
Duplicate of #2677

**Closed** 2024-09-25 14:28 UTC
Labels: support
