### ISSUE TITLE
Serde default behavior is strange

### ISSUE THREAD

**Issue by breeswish** [serde-rs/serde#1254] opened 2018-05-10 12:38 UTC
```rust
#[macro_use]
extern crate serde_derive;

extern crate serde;
extern crate serde_json;

#[derive(Serialize, Deserialize, Debug)]
#[serde(default)]
struct NodeConfig {
    size: usize,
}

impl Default for NodeConfig {
    fn default() -> Self {
        NodeConfig { size: 0 }
    }
}

#[derive(Serialize, Deserialize, Debug)]
#[serde(default)]
struct ClusterConfig {
    node1: NodeConfig,
    node2: NodeConfig,
}

impl Default for ClusterConfig {
    fn default() -> Self {
        ClusterConfig {
            node1: NodeConfig { size: 1 },
            node2: NodeConfig { size: 2 },
        }
    }
}

fn main() {
    let deserialized: ClusterConfig = serde_json::from_str("{ \"node1\": {} }").unwrap();
    println!("deserialized = {:?}", deserialized);
}
```

The behavior is somewhat strange.

- If the input is `{}`, we will get `ClusterConfig { node1: NodeConfig { size: 1 }, node2: NodeConfig { size: 2 } }`.

- But if the input is `{ "node1": {} }`, we will get `ClusterConfig { node1: NodeConfig { size: 0 }, node2: NodeConfig { size: 2 } }`.

In both cases, we are actually not supplying any information about the field "size", but it results in different default values for the "size" field. I know this is an indented result according to current implementations, but isn't itself wired?

It becomes more obvious when serde is used as configurations with some format like toml or yaml:

```toml
# nothing
```

leaves `node1.size == 1`, while

```toml
[node1]
```

leaves `node1.size == 0`.

**Comment by dtolnay** [comment] 2018-05-10 14:52
This is the intended behavior -- the `default` attribute governs what happens *when a field is missing*. So in `{"node1":{}}` the "node2" field is missing and receives its default value with size=2, and the "size" field of "node1" is missing and receives its default value of 0. In `{}` both "node1" and "node2" are missing and receive their default values with size=1 and size=2.

If you want to allow a missing "size" field and use a default that depends on which field of ClusterConfig we are, the simplest way would be to capture that "node1" was present but "size" was missing such as by using `Option<usize>` for the size, then interpreting `None` as the correct default value after deserialization.

```rust
#[derive(Deserialize)]
struct NodeConfig {
    size: Option<usize>,
}

#[derive(Deserialize)]
#[serde(default)]
struct ClusterConfig {
    node1: NodeConfig,
    node2: NodeConfig,
}
```

You can also deal with this during deserialization and avoid changing the data structures as follows.

```rust
use serde::{Deserialize, Deserializer};

struct NodeConfig {
    size: usize,
}

#[derive(Deserialize)]
#[serde(default)]
struct ClusterConfig {
    #[serde(deserialize_with = "de_node1")]
    node1: NodeConfig,
    #[serde(deserialize_with = "de_node2")]
    node2: NodeConfig,
}

macro_rules! deserialize_node_config {
    ($f:ident, size = $size:expr) => {
        fn $f<'de, D>(deserializer: D) -> Result<NodeConfig, D::Error>
        where
            D: Deserializer<'de>,
        {
            #[derive(Deserialize)]
            struct NodeConfigHelper {
                size: Option<usize>,
            }

            let helper = NodeConfigHelper::deserialize(deserializer)?;
            Ok(NodeConfig {
                size: helper.size.unwrap_or($size),
            })
        }
    }
}

deserialize_node_config!(de_node1, size = 1);
deserialize_node_config!(de_node2, size = 2);
```

**Comment by breeswish** [comment] 2018-05-11 03:50
@dtolnay Thanks a lot! I'm indeed using a workaround just like your example 1, and your example 2 gives me ideas about making them even better!

I understand it is intended. If this behaviour is not going to be changed in the near future, I would like to see a note in the documentation about the default feature to hint users about the behaviour and its consequences (i.e. what you can expect to work and what can't).

**Comment by BusyJay** [comment] 2018-05-11 07:14
Is it a reasonable behavior? Everyone chooses to override a field's default value for a reason, which usually means that it should be respected during deserialization. In what use cases that will someone want a default value A when the field is missing, while another default value B when the field is (partially) specified?

**Comment by dtolnay** [comment] 2018-05-19 04:54
I am closing the issue because I don't intend to change the behavior of `#[serde(default)]`, but I would love help improving our documentation of the current behavior. Thanks!

**Closed by dtolnay** 2018-05-19 04:54 UTC
