### ISSUE TITLE
flat vec

### ISSUE THREAD

**Issue by cathaysia** [serde-rs/serde#2504] opened 2023-07-11 03:21 UTC
Currently, flatten attr can be apply struct and map, if it's possible apply it to vec? If not, serde should throw a error at compile time but not runtime.

**Comment by Mingun** [comment] 2023-07-11 04:23
Generating a compile-time error should be possible, if flattenable types would implement some trait. The error will be the ordinally compiler error about missing trait implementation. That is the course that will help to resolve #1183 also, so I find it very promising. On syntax level (on which derive macros works) it is impossible to implement this.

There also exists a feature request for this: #1905

**Comment by dtolnay** [comment] 2023-07-11 23:23
Closing as a duplicate of #1905.

**Closed by dtolnay** 2023-07-11 23:23 UTC
