### ISSUE TITLE
Bug: alias and flatten don't work together

### ISSUE THREAD

**Issue by wcarmon** [serde-rs/serde#2341] opened 2022-12-15 18:01 UTC
The code below demonstrates that `flatten` and `alias` features of serde don't work together.

Below shows examples from both `serde_json` and `toml` library.

# Env
- lib version: `toml = "0.5.9"`
- lib version: `serde_json = "1.0.89"`
- cargo version: `cargo 1.67.0-nightly (ba607b23d 2022-11-22)`
- serde version `serde = { version = "1.0.147", features = ["derive"] }`
- serde [flattening](https://serde.rs/attr-flatten.html#struct-flattening) feature
- serde [alias](https://serde.rs/field-attrs.html#alias) feature

Here is an [MWE](https://en.wikipedia.org/wiki/Minimal_reproducible_example) which demonstrates the bug
```rust
use serde::Deserialize;

#[derive(Deserialize)]
struct Inner {
    #[serde(alias = "myBool")]
    b: bool,

    i: i64,
}

#[derive(Deserialize)]
struct Outer {
    #[serde(flatten)]
    a: Inner,
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn works_as_expected_in_toml() {
        let t_str = r#"
b = true
i = 7
"#;

        let res: Result<Outer, toml::de::Error> = toml::from_str(t_str);
        let got = res.unwrap();

        assert_eq!(true, got.a.b);
        assert_eq!(7, got.a.i);
    }

    #[test]
    fn shows_bug_in_toml() {
        let t_str = r#"
myBool = true
i = 7
"#;

        let res: Result<Outer, toml::de::Error> = toml::from_str(t_str);
        let got = res.unwrap(); // *** incorrect behavior manifests here

        assert_eq!(true, got.a.b);
        assert_eq!(7, got.a.i);
    }

    #[test]
    fn works_as_expected_in_json() {
        let j_str = r#"
{
    "b": true,
    "i": 7
}
"#;

        let res = serde_json::from_str::<Outer>(j_str);
        let got = res.unwrap();

        assert_eq!(true, got.a.b);
        assert_eq!(7, got.a.i);
    }

    #[test]
    fn shows_bug_in_json() {
        let j_str = r#"
{
    "myBool": true,
    "i": 7
}
"#;

        let res = serde_json::from_str::<Outer>(j_str);
        let got = res.unwrap(); // *** incorrect behavior manifests here

        assert_eq!(true, got.a.b);
        assert_eq!(7, got.a.i);
    }
}
```

# Related
- https://github.com/toml-rs/toml/issues/389
- (Maybe related): https://github.com/serde-rs/serde/issues/2236

**Comment by jonasbb** [comment] 2022-12-15 19:12
This is a known problem: https://github.com/serde-rs/serde/issues/1504.

**Comment by Mingun** [comment] 2023-05-09 08:13
This was fixed (partially) by #2387, the in-place part is fixed in #2443

**Comment by dtolnay** [comment] 2023-07-09 02:47
Closing as a duplicate of #2188.

**Closed by dtolnay** 2023-07-09 02:47 UTC
