### ISSUE TITLE
Add option to include variant error messages when deserializing untagged enum fails

### ISSUE THREAD

**Issue by DzenanJupic** [serde-rs/serde#2143] opened 2021-12-25 15:32 UTC
Currently, when the deserialization of an untagged enum fails, the error message contains no information why this is the case. It would be really helpful if there'd be an option to include the error message of each variant.

So instead of
```
data did not match any variant of untagged enum <ENUM>
```
something like
```
data did not match any variant of untagged enum <ENUM>. Errors:\n<ERR1>\n<ERR2>
```

**Comment by dtolnay** [comment] 2022-01-23 00:43
Duplicate of #773.

**Closed by dtolnay** 2022-01-23 00:43 UTC
