### ISSUE TITLE
untagged enum variant results in null value

### ISSUE THREAD

**Issue by avnerbarr** [serde-rs/serde#2060] opened 2021-07-27 10:46 UTC
I need to serialize an enum with untagged but if the enum doesn't have associated data it is serialized as "null" rather than the "plain text" value of that enum

here is a playground example

https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=b6de38851cd032c45ca162416c0f4c65

```
use serde::{Serialize,Deserialize};
#[derive(Serialize, Deserialize)]
#[serde(untagged)]
pub enum Config {
    Default,
    Custom(CustomConfig)
}

#[derive(Serialize, Deserialize)]
pub struct CustomConfig {
    id: String,
    age: i32
}

#[derive(Serialize, Deserialize)]

pub struct Parent {
    config: Config,
    name: String
}

fn main() {
    let p1 = Parent { config: Config::Default, name: "First".to_string() };
    let p2 = Parent { config: Config::Custom(CustomConfig{id: "id1".to_string(), age: 42}), name: "Second".to_string() };
    
    let v = vec![p1,p2];
    
    let res = serde_json::to_string_pretty(&v).unwrap();
    println!("{}", res);
}


[
  {
    "config": null, <<<<<<<<< this is invalid and won't serialize later, also ugly :) can we replace with the textual value?
    "name": "First"
  },
  {
    "config": {
      "id": "id1",
      "age": 42
    },
    "name": "Second"
  }
]
```

**Comment by Mingun** [comment] 2021-07-27 14:09
Look at the [`#[serde(skip_serializing_if = "path")]`](https://serde.rs/field-attrs.html#skip_serializing_if) attribute:
https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=b6de38851cd032c45ca162416c0f4c65

**Comment by omid** [comment] 2021-09-29 15:58
seems like a duplicate of https://github.com/serde-rs/serde/issues/1560

**Comment by dtolnay** [comment] 2022-01-23 02:21
Closing as a duplicate of #1560.

**Closed by dtolnay** 2022-01-23 02:21 UTC
