### ISSUE TITLE
Overconstrained implementation of Serialize

### ISSUE THREAD

**Issue by Kixunil** [serde-rs/serde#1793] opened 2020-05-02 12:22 UTC
When deriving `Serialize`, the resulting code seems to overconstrain the implementation.

[playground example of this problem](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=81eac9e1e8b36f61c7efec00514b8dd6)

The derive macro seems to require that `T: Serialize` instead of `Foo<T>: Serialize` for some reason. This makes it impossible to write wrappers for implementing `Serialize` in terms of other trait.

**Comment by jonasbb** [comment] 2020-05-02 13:34
The defaults of the derive are simple and always add the `Serialize` bound for each generic type. However, you can overwrite the trait bounds like `#[serde(bound = "T: MyTrait")]`.
https://serde.rs/container-attrs.html#bound

**Comment by Kixunil** [comment] 2020-05-02 14:14
Glad to hear there's a usable workaround. Doing the right thing by default would be nicer though.

**Comment by dtolnay** [comment] 2020-05-02 16:19
Duplicate of #370.

**Closed by dtolnay** 2020-05-02 16:19 UTC

**Comment by dtolnay** [comment] 2020-05-02 16:22
See https://github.com/dtolnay/syn/issues/370 -- we tried less constrained bounds in 0.7 and it turned out to be worse.

**Comment by Kixunil** [comment] 2020-05-02 16:28
Damn, that sucks, thanks for pointers!
