### ISSUE TITLE
flattened untagged options parse as None instead of returning an error when a field has an incorrect type

### ISSUE THREAD

**Issue by lovasoa** [serde-rs/serde#2149] opened 2022-01-07 17:33 UTC
Hello, and thanks for this awesome library !

I have the following structs

```rust
struct Config {
    option_1: i32,
    subconfig: Option<SubConfig>,
}

struct SubConfig {
    option_2: i32,
}
```

And I would like to be able to parse 

```json
{ "option_1" : 1 }
```

and

```json
{ "option_1" : 1,  "option_2" : 2 }
```

but the following should fail to parse and return an error : 

```json
{ "option_1" : 1,  "option_2" : "xxx" }
```

Currently, I am using 

```rust
use serde::{Serialize, Deserialize};

#[derive(Serialize, Deserialize, Debug)]
#[serde(deny_unknown_fields)]
struct Config {
    option_1: i32,
    #[serde(flatten)]
    subconfig: Option<SubConfig>,
}

#[derive(Serialize, Deserialize, Debug)]
#[serde(deny_unknown_fields)]
struct SubConfig {
    option_2: i32,
}

fn main() {
    println!("{:?}", serde_json::from_str::<Config>(r#"{
        "option_1": 10,
        "option_2": "xxx"
    }"#));
}
```

But it returns

```rust
Ok(Config { option_1: 10, subconfig: None })
```

instead of the expected error. 

If I have `#[serde(deny_unknown_fields)]` in both my structs, then where did the unknown field go?

This may be related to #1255

**Comment by dtolnay** [comment] 2022-01-23 04:41
Closing as a duplicate of #1880.

**Closed by dtolnay** 2022-01-23 04:41 UTC
