### ISSUE TITLE
Support Go-isk Tags

### ISSUE THREAD

**Issue by TroyKomodo** [serde-rs/serde#2800] opened 2024-08-15 00:54 UTC
```rs
#[derive(serde::Serialize, serde::Deserialize)]
struct MyCustomStruct {
  #[serde(with_tag("bson", with = "bson::serde_helpers::chrono_datetime_as_bson_datetime"))]
  #[serde(with_tag("custom-binary", with = "magic_binary"))]
  time: chrono::DateTime<chrono::Utc>,
}

mod magic_binary {
  fn serialize<S: serde::Serializer>(time: chrono::DateTime<chrono::Utc>, ser: S) -> Result<S::Ok, S::Error> {
    s.serialize_i64(time.timestamp_nanos_opt().unwrap())
  }
  
  fn deserialize<'de, D>(D) -> Result<T, D::Error> where D: Deserializer<'de> {
    let nanos = i64::deserialize(D)?;

    Ok(chrono::DateTime::from_timestamp_nanos(nanos))
  }
}

struct BsonSerializer {
  tag: String
}

impl Serializser for BsonSerializer {
  fn uses_tag(&self) -> Option<&str> {
    Some(self.tag.as_ref())
  }
}
```

Allow for some mechanism to specify specific options depending on the encoder/decoder.

perhaps even make the tag required and then impl a default on the trait to be the name of the module that is being compiled?

**Comment by dtolnay** [comment] 2024-08-16 00:00
This issue is a duplicate of #2620.

**Closed by dtolnay** 2024-08-16 00:00 UTC
