### ISSUE TITLE
`#[serde(default)]` is ignored in newtype structs, newtype variants, tuple structs and tuple variants

### ISSUE THREAD

**Issue by hcpl** [serde-rs/serde#1418] opened 2018-11-02 00:15 UTC
```rust
#[derive(Deserialize)]
struct Foo;

#[derive(Deserialize)]
// should error with "the trait `std::default::Default` is not implemented for `Foo`"
struct Boom(#[serde(default)] Foo);

#[derive(Deserialize)]
// should error with "the trait `std::default::Default` is not implemented for `Foo`"
struct Bar(#[serde(default)] Foo, Foo);

#[derive(Deserialize)]
enum Badum {
    // should error with "the trait `std::default::Default` is not implemented for `Foo`"
    Tss(#[serde(default)] Foo),
}

#[derive(Deserialize)]
enum Baz {
    // should error with "the trait `std::default::Default` is not implemented for `Foo`"
    Spam(#[serde(default)] Foo, Foo),
}
```

EDIT: also ignored in newtype structs and newtype variants.

[Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2015&gist=69ffc79da4aab2686ef1113a1746bcc3).

**Comment by Mingun** [comment] 2023-05-28 15:17
Currently only
```rust
#[derive(Deserialize)]
enum Badum {
    // should error with "the trait `std::default::Default` is not implemented for `Foo`"
    Tss(#[serde(default)] Foo),
}
```
case doesn't produce an error, because of #2105, so this issue can be closed as duplicate of #2105.

**Closed** 2023-05-30 10:15 UTC
Labels: derive
