### ISSUE TITLE
Document (more prominently?) that serde_json allows sequences to be deserialized into structs

### ISSUE THREAD

**Issue by tbu-** [serde-rs/serde#2438] opened 2023-05-01 11:20 UTC
Last time I saw this was https://old.reddit.com/r/rust/comments/1332t9b/ji7oo8m/, but I've also seen it earlier and found it surprising both times.

Basically both `{"hello": "test", "value": 42}` (expected) and `["test", 42]` deserialize perfectly fine into the following struct:
```
#[derive(Serialize, Deserialize)]
pub struct HelloParams {
    hello: String, 
    value: i32,
}
```

Since this is not mentioned anywhere, this can accidentally become a used API when serde is used to parse JSON ([Hyrum's law](https://en.wikipedia.org/wiki/Hyrum%27s_law)).

It would be nice if this could be featured somewhere prominently in the docs. I couldn't actually find it there, even looking for it.

**Comment by Mingun** [comment] 2023-05-28 16:04
Probably `serde_json` should not call `visit_seq` if `deserialize_map` / `deserialize_struct` was requested by the type. Then deserialization structs from JSON arrays would be impossible. That also can be a configurable behavior of `serde_json` deserializer.

**Comment by Mingun** [comment] 2023-05-28 19:23
Actually, this is duplicate of #1587.

**Closed** 2023-05-30 09:50 UTC

**Comment by tbu-** [comment] 2023-05-30 22:53
I don't see how this is a duplicate, @oli-obk. This is about documenting behavior of `serde_json`, not about changing it. The other issue asks for behavioral changes that are likely backward incompatible and thus unlikely to happen.
