### ISSUE TITLE
Ability to use default value even if set to null

### ISSUE THREAD

**Issue by est31** [serde-rs/serde#1098] opened 2017-11-23 09:15 UTC
default does not treat a field being set to `null` equal to the field being emitted. More concretely, the following code will panic in the line where it attempts to deserialize `request_c`:

```rust
#[macro_use]
extern crate serde_derive;

extern crate serde;
extern crate serde_json;

#[derive(Serialize, Deserialize, Debug)]
struct Request {
    #[serde(default = "Priority::lowest")]
    priority: Priority,
}

#[derive(Serialize, Deserialize, Debug)]
enum Priority { ExtraHigh, High, Normal, Low, ExtraLow }
impl Priority {
    fn lowest() -> Self { Priority::ExtraLow }
}

fn main() {

    let request_a: Request = serde_json::from_str(r"{}").unwrap();
    println!("{:?}", request_a);

    let request_b: Request = serde_json::from_str(r#"{"priority": "High"}"#).unwrap();
    println!("{:?}", request_b);

    let request_c: Request = serde_json::from_str(r#"{"priority": null}"#).unwrap();
    //^~ PANIC: ErrorImpl { code: ExpectedSomeValue, line: 1, column: 14 }
    println!("{:?}", request_c);

}
```

The data I want to process sometimes has its field set, sometimes it is set to `null`, and sometimes it is omitted. I want to set a default for when it is null or omitted.

This doesn't need to be the default behaviour but having sth like `#[serde(default_on_null)]` would be really nice :). Thanks to @oli-obk  suggesting that on IRC.

**Comment by dtolnay** [comment] 2017-11-23 22:52
I am open to supporting this better. For now the current workaround would be a `deserialize_with` function that handles null.

```rust
use serde::{Deserialize, Deserializer};

#[derive(Serialize, Deserialize, Debug)]
struct Request {
    #[serde(default = "Priority::lowest", deserialize_with = "nullable_priority")]
    priority: Priority,
}

fn nullable_priority<'de, D>(deserializer: D) -> Result<Priority, D::Error>
    where D: Deserializer<'de>
{
    let opt = Option::deserialize(deserializer)?;
    Ok(opt.unwrap_or_else(Priority::lowest))
}
```

**Comment by est31** [comment] 2017-11-23 23:11
@dtolnay oh thanks. That's nice and small compared to the monster that I wrote :)...

**Comment by dtolnay** [comment] 2019-01-06 05:13
A `default_on_null` function would be a reasonable addition to a Serde helper library such as [serde-aux](https://crates.io/crates/serde-aux) or [serde_with](https://crates.io/crates/serde_with). I am closing this issue because I don't think we need to introduce a new Serde attribute for this use case.

**Closed by dtolnay** 2019-01-06 05:13 UTC
Labels: derive

**Comment by folex** [comment] 2020-07-16 16:59
Hi! Thank you for an awesome serde :)

Sorry for writing to an old thread, just wanted to know why there's a need for a separate attribute? Couldn't `default` do the trick?

If I understand correctly, in the case of JSON deserializing `#[serde(default)]` struct from "{}" yields default value, while deserializing from "null" gives error:

> invalid type: null, expected struct

Here's an example code
https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=9cda0c82d5f144615db93666bee84d24

Is that an expected behaviour, or an inconsistency of `serde`/`serde_json`?  I would expect `{}` and `null` both yield a default value.

Thanks in advance!

**Comment by gabhijit** [comment] 2021-01-15 07:37
Since, search results land to this page - Here's something that can use 'default' 

```rust
// Omitting other derives, for brevity 
#[derive(Deserialize)]
struct Foo {
   #[serde(deserialize_with = "deserialize_null_default")]
   value: String, 
}

fn deserialize_null_default<'de, D, T>(deserializer: D) -> Result<T, D::Error>
where
    T: Default + Deserialize<'de>,
    D: Deserializer<'de>,
{
    let opt = Option::deserialize(deserializer)?;
    Ok(opt.unwrap_or_default())
}
```

[playground link] (https://play.integer32.com/?version=stable&mode=debug&edition=2018&gist=d1b67fae798e958b377c622fd009de14)

**Comment by IGJAmpere** [comment] 2022-12-01 12:04
> Is that an expected behaviour, or an inconsistency of `serde`/`serde_json`? I would expect `{}` and `null` both yield a default value.

It is an expected behaviour. The default value is used when the variable is not specified. `null` can be a specification of the variable, as sometimes it carries very useful information (can be interpreted as _infinite_, or _unset_), which might be relevant to different use-cases.

So, null -> default cases are a specific thing, and should be specifically determined.

**Comment by ollyde** [comment] 2024-03-28 14:40
Am I missing something here guys?

No one has explained if there was an additional library needed?

<img width="637" alt="Screenshot 2024-03-28 at 15 39 07" src="https://github.com/serde-rs/serde/assets/6940726/ec7ff282-5bb9-4b51-948a-27c76c62ebc7">

**Comment by Kochiyama** [comment] 2024-04-09 20:03
> Am I missing something here guys?
> 
> No one has explained if there was an additional library needed?
> 
> <img alt="Screenshot 2024-03-28 at 15 39 07" width="637" src="https://private-user-images.githubusercontent.com/6940726/317768847-ec7ff282-5bb9-4b51-948a-27c76c62ebc7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI2OTI5MDksIm5iZiI6MTcxMjY5MjYwOSwicGF0aCI6Ii82OTQwNzI2LzMxNzc2ODg0Ny1lYzdmZjI4Mi01YmI5LTRiNTEtOTQ4YS0yN2M3NmM2MmViYzcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQwOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MDlUMTk1NjQ5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YzFlYzNhMDAzYjE2NzEwMjgwNGM2ODI1YmI4M2FmMzEyMDRmNTAwYmNlYjVjNWZiYzdkYjk5ZTVjYjZkMjFmYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.8FBTHxWWE7Las7SVCMqrtQHb57yuQxPIyNGkalQ1rLo">

You need to define this function manually in some place in your file.

**Comment by mhnap** [comment] 2024-05-31 08:58
> Since, search results land to this page - Here's something that can use 'default'
> 
> ```rust
> // Omitting other derives, for brevity 
> #[derive(Deserialize)]
> struct Foo {
>    #[serde(deserialize_with = "deserialize_null_default")]
>    value: String, 
> }
> 
> fn deserialize_null_default<'de, D, T>(deserializer: D) -> Result<T, D::Error>
> where
>     T: Default + Deserialize<'de>,
>     D: Deserializer<'de>,
> {
>     let opt = Option::deserialize(deserializer)?;
>     Ok(opt.unwrap_or_default())
> }
> ```
> 
> [playground link] ([play.integer32.com/?version=stable&mode=debug&edition=2018&gist=d1b67fae798e958b377c622fd009de14](https://play.integer32.com/?version=stable&mode=debug&edition=2018&gist=d1b67fae798e958b377c622fd009de14))

Great solution! But need to remember that `#[serde(default)]` attribute is still needed if we want to use the `Default::default()` if the value is not present when deserializing ([playground](https://play.integer32.com/?version=stable&mode=debug&edition=2018&gist=683a11b953612896a0684e825ff51ae0)).
