### ISSUE TITLE
It'd be nice to be able to set a default value without needing a function

### ISSUE THREAD

**Issue by alexschrod** [serde-rs/serde#2254] opened 2022-08-08 06:11 UTC
I could be missing something, but I've got this definition:
```rust
#[derive(Debug, Deserialize)]
struct PropertyValue {
    #[serde(default = "default_property_type")]
    pub r#type: String,
    pub value: String,
}
fn default_property_type() -> String {
    "string".to_owned()
}
```
It feels excessive to have a whole function just for this, it'd be nice if I could do something like `#[serde(default = || "string".to_owned())]` or maybe `#[serde(default_value = "string")]`.

**Comment by rustonaut** [comment] 2022-10-24 11:05
Proc macros do support code snippets.

So instead of `#[serde(default_value = "1")]` you can have `#[serde(default_value = 1)]` or even
something like `#[serde(default_value = Some("foo".into()))]` or  ``.

```rust
struct Foo {
    #[serde(default_value = 1)]
    num: u16,
    
    #[serde(default_value = u16::MAX)]
    num: u16,
    
    //or even
    
    #[serde(default_value = Cow::Borrowed(APPLICATION_NAME))]
    name: Cow<'static, str>,
```

Alternatively we could also change `default` to accept snippets which are functions e.g.:

```rust
struct Foo {
    #[serde(default = || "foobar".into() )]
    field: String,
    
    #[serde(default = || format!("foo-bar-{APPLICATION_NAME}")]
    field2: String,
```

Through there are two drawbacks:

1. AFIK in the very early stable days of rust this was not possible, I'm not sure if 1.13 is new enough we would have to test it.
2. `syn` has with `Meta` a nice helper to parse proc-macro attributes, but that helper doesn't support this. We don't have to use it as it's not reducing complexity by that much, but this means you probably would need some preparing PRs which do make sure we can parse attributes as `<path> "(" <key> [ "=" <tokens> ] ")" `

**Comment by kangalioo** [comment] 2022-10-31 11:26
Duplicate of #368

**Closed** 2023-07-09 08:40 UTC

**Comment by ken0x0a** [comment] 2023-07-11 11:34
@dtolnay
I couldn't find commits to close this issue in these 2 days and couldn't find attribute like `default_value` e.t.c.
Did you want to close this?

**Comment by oli-obk** [comment] 2023-07-11 12:33
This issue is a duplicate of https://github.com/serde-rs/serde/issues/368

You can read and subscribe to the other issue

**Comment by jendakol** [comment] 2024-09-27 08:11
For a random reader... check out https://crates.io/crates/serde-inline-default
