### ISSUE TITLE
Type parameters break transparent deserialization, doesn't automatically skip PhantomData

### ISSUE THREAD

**Issue by azriel91** [serde-rs/serde#1660] opened 2019-10-30 02:20 UTC
Hi, found that when a struct has type parameters, `serde` no longer deserializes the non-`PhantomData` inner field of a named or tuple struct transparently, and also doesn't seem to ignore `PhantomData`.

A minimal example is on the ([playpen](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=e657c5cacc330084b367814db5edd1a8)). Tested using `serde` version `1.0.102`

#### Case one: Tuple Struct

Given this struct:

```rust
#[derive(Debug, Deserialize)]
struct Sequences<S, F>(HashMap<String, S>, PhantomData<F>)
where
    S: AsRef<Sequence<F>>,
    F: AsRef<u32>;

#[derive(Debug, Deserialize)]
struct Definition {
    sequences: Sequences<Sequence<Frame>, Frame>,
}
```

and this yaml:

```yaml
sequences:
  one:
    frames: [{ value: 123 }]
```

Upon deserialization, this error is returned:

```
"invalid type: map, expected tuple struct Sequences", Some(Pos { marker: Marker { index: 17, line: 3, col: 5 }, path: "sequences" })
```

#### Case Two: PhantomData not skipped automatically

If I use this as the `Sequences` struct instead:

```rust
#[derive(Debug, Deserialize)]
struct Sequences<S, F>
where
    S: AsRef<Sequence<F>>,
    F: AsRef<u32>,
{
    #[serde(flatten)]
    sequences: HashMap<String, S>,
    // note: no #[serde(skip)]
    marker: PhantomData<F>,
}
```

Then this error is returned:

```
"missing field `marker`", Some(Pos { marker: Marker { index: 17, line: 3, col: 5 }, path: "sequences" })
```

---

Workaround is to:

* Use the named struct
* Add `#[serde(flatten)]` to the first field.
* Add `#[serde(skip)]` to the `PhantomData`

**Comment by dtolnay** [comment] 2019-11-24 23:30
Hi @azriel91 -- I am trying to understand what this issue is about. Doesn't Serde never automatically skip PhantomData or transparently forward to a tuple struct field? How does the presence of type parameters come into play?

I tried your two examples without type parameters and the behavior is the same as the messages you showed, as I would expect:

#### Case one: tuple struct

```rust
use serde::Deserialize;
use std::collections::HashMap;
use std::marker::PhantomData;

#[derive(Debug, Deserialize)]
struct Definition {
    sequences: Sequences,
}

#[derive(Debug, Deserialize)]
struct Sequences(HashMap<String, Sequence>, PhantomData<Frame>);

#[derive(Debug, Deserialize)]
struct Sequence {
    frames: Vec<Frame>,
}

#[derive(Debug, Deserialize)]
struct Frame {
    value: u32,
}

const YAML: &str = r#"
sequences:
  one:
    frames: [{ value: 123 }]
"#;

fn main() {
    eprintln!("{}", serde_yaml::from_str::<Definition>(YAML).unwrap_err());
}
```

```console
sequences: invalid type: map, expected tuple struct Sequences at line 3 column 6
```

#### Case two: PhantomData

```rust
use serde::Deserialize;
use std::collections::HashMap;
use std::marker::PhantomData;

#[derive(Debug, Deserialize)]
struct Definition {
    sequences: Sequences,
}

#[derive(Debug, Deserialize)]
struct Sequences {
    #[serde(flatten)]
    sequences: HashMap<String, Sequence>,
    marker: PhantomData<Frame>,
}

#[derive(Debug, Deserialize)]
struct Sequence {
    frames: Vec<Frame>,
}

#[derive(Debug, Deserialize)]
struct Frame {
    value: u32,
}

const YAML: &str = r#"
sequences:
  one:
    frames: [{ value: 123 }]
"#;

fn main() {
    eprintln!("{}", serde_yaml::from_str::<Definition>(YAML).unwrap_err());
}
```

```console
sequences: missing field `marker` at line 3 column 6
```

---

I'll close the issue because I think both of these are working correctly, but if there is inconsistent behavior caused by type parameters please provide a minimal example that demonstrates it.

**Closed by dtolnay** 2019-11-24 23:30 UTC

**Comment by azriel91** [comment] 2019-11-25 00:02
> Doesn't Serde never automatically skip PhantomData or transparently forward to a tuple struct field?

Hm, for some reason I believed it did. It does for single field newtype structs -- removing the `PhantomData` causes the deserialization to return `Ok(..)`. Can't seem to find where I read it, but the code works anyway.
(mistakenly) I thought a `PhantomData` second field would be ignored. Must've been using too many other proc macro crates.

The type parameters are a red herring -- I must've only ever had the `PhantomData` second field on a struct with type parameters.

Well, mystery solved
