### ISSUE TITLE
Compilation fails inside serde macro

### ISSUE THREAD

**Issue by Sycration** [serde-rs/serde#2595] opened 2023-08-21 08:43 UTC
All of this is on the `rust:1.71` docker image:

Running `cargo install sqlx-cli --no-default-features --features rustls,postgres` fails with a strange error: 
```
24.86 error[E0507]: cannot move out of `*self` which is behind a shared reference
24.86   --> /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/cargo_metadata-0.14.2/src/diagnostic.rs:95:24
24.86    |
24.86 95 | #[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, Hash)]
24.86    |                        ^^^^^^^^^
24.86    |                        |
24.86    |                        data moved here
24.86    |                        move occurs because `unrecognized` has type `Applicability`, which does not implement the `Copy` trait
24.86    |
24.86    = note: this error originates in the derive macro `Serialize` (in Nightly builds, run with -Z macro-backtrace for more info)
24.86 help: consider borrowing here
24.86    |
24.86 95 | #[derive(Debug, Clone, &Serialize, Deserialize, PartialEq, Eq, Hash)]
24.86    |                        +
24.86 
24.91 error[E0507]: cannot move out of `*self` which is behind a shared reference
24.91    --> /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/cargo_metadata-0.14.2/src/messages.rs:101:24
24.91     |
24.91 101 | #[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, Hash)]
24.91     |                        ^^^^^^^^^
24.91     |                        |
24.91     |                        data moved here
24.91     |                        move occurs because `unrecognized` has type `Message`, which does not implement the `Copy` trait
24.91     |
24.91     = note: this error originates in the derive macro `Serialize` (in Nightly builds, run with -Z macro-backtrace for more info)
24.91 help: consider borrowing here
24.91     |
24.91 101 | #[derive(Debug, Clone, &Serialize, Deserialize, PartialEq, Eq, Hash)]
24.91     |                        +
24.91 
25.06 For more information about this error, try `rustc --explain E0507`.
25.07 error: could not compile `cargo_metadata` (lib) due to 2 previous errors
```

full log:  [log.txt](https://github.com/serde-rs/serde/files/12394049/log.txt)

But running `cargo install sqlx-cli --no-default-features --features rustls,postgres --git https://github.com/launchbadge/sqlx --locked` succeeds.

full log: [log-works.txt](https://github.com/serde-rs/serde/files/12394077/log-works.txt)

**Comment by Sycration** [comment] 2023-08-21 08:44
I first observed this in https://github.com/launchbadge/sqlx/issues/2704

**Comment by oli-obk** [comment] 2023-08-21 08:55
I believe this was fixed in https://github.com/serde-rs/serde/releases/tag/v1.0.185 so you may just have to `cargo update`

**Comment by oli-obk** [comment] 2023-08-21 11:26
Duplicate of https://github.com/serde-rs/serde/pull/2592

**Closed by oli-obk** 2023-08-21 11:26 UTC
