### ISSUE TITLE
Rename `try!` macro for 2018 compatibility

### ISSUE THREAD

**Issue by withoutboats** [serde-rs/serde#1385] opened 2018-09-12 00:57 UTC
serde derive uses a custom defined `try!` macro internally, rather than `?`. However, `try` is becoming a reserved word in the 2018 edition. For compatibility with 2018, it would be ideal if you renamed this macro.

**Comment by Mark-Simulacrum** [comment] 2018-09-12 01:10
Hm, it's not clear to me that Serde should be responsible for making this change? That is, when/if Serde migrates to 2018 edition then it should but prior to that it was my understanding that edition hygiene should not require this -- am I wrong about that?

**Comment by withoutboats** [comment] 2018-09-12 01:16
You're correct that users should not get edition related warnings from the expansion of external macros.

**Comment by withoutboats** [comment] 2018-09-12 19:04
According to the user report on internals, the compiler might not be successfully performing edition hygiene in all cases. Obviously, this is a bug in the compiler. But this seems like a small change to serde_derive that would help mitigate edition hygiene bugs and keep them from impacting the many users of this crate.

**Comment by dtolnay** [comment] 2018-09-13 06:01
Internals thread: [*Trying Rust2018, getting many warnings on \`try\` is a keyword*](https://internals.rust-lang.org/t/trying-rust2018-getting-many-warnings-on-try-is-a-keyword/8375)

I am not able to reproduce the warnings reported there. If anyone succeeds in reproducing and can explain why this is something that a large number of users would encounter, then I can reconsider, but for now I am closing this issue. Thanks anyway! We'll take care of this when moving Serde to 2018 but don't need an issue to track this specific piece of that work.

Hopefully this helps track down the remaining places were edition hygiene is going wrong. I believe our use of `try` is within the space of what needs to be supported.

**Closed by dtolnay** 2018-09-13 06:01 UTC

**Comment by alisianoi** [comment] 2020-06-02 17:24
>  If anyone succeeds in reproducing and can explain why this is something that a large number of users would encounter, then I can reconsider, but for now I am closing this issue.

For me there is a warning in my emacs. My configuration ([relevant part is lines 80 to 90](https://github.com/alisianoi/config-files/blob/d73debf14da84f20b0fc12e35be73956b5744424/.emacs#L80)) is inspired by a fairly common [configuration for Rust development from reddit](https://www.reddit.com/r/rust/comments/a3da5g/my_entire_emacs_config_for_rust_in_fewer_than_20/). The warning is triggered whenever I save the file, my screen gets split in two halves and the bottom half shows the exception (twice for whatever reason):

![Screenshot from 2020-06-02 19-15-15](https://user-images.githubusercontent.com/962850/83549503-b5b24480-a505-11ea-9a81-f6b651095b16.png)
 
If this is theoretically just an issue of replacing ~200 occurances of `try!` in the codebase, I can do that. So far, I've replaced all `try!` occurances in two files and `cargo test` still works:

1. serde/src/ser/mod.rs
1. serde/src/ser/impls.rs

My Rust skills are limited, so I actually have no idea if replacing `try!` with `?` will break things

**Comment by dtolnay** [comment] 2020-06-02 17:40
That looks like the emacs integration is building the code using the wrong edition. Is there a bug report about that?

**Comment by alisianoi** [comment] 2020-06-02 22:32
At my previous comment, my `rustup toolchain list` looked like this:

```
nightly-2019-08-27-x86_64-unknown-linux-gnu
nightly-2020-02-27-x86_64-unknown-linux-gnu
nightly-2020-04-08-x86_64-unknown-linux-gnu
nightly-x86_64-unknown-linux-gnu (default)
```

I removed every toolchain with `rustup toolchain uninstall` and then reinstalled `nightly` like so:

```
$ rustup toolchain install nightly
$ rustup toolchain list
nightly-x86_64-unknown-linux-gnu (default)
```

I also removed all of my rust-related `.emacs` configurations and only left the "run rustfmt when I press save" configuration and restarted my emacs:

```
(setq rust-format-on-save t)                                                                                                                                   
```

With that, the error message changed _slightly_ but is still largely the same:

![Screenshot from 2020-06-03 00-29-52](https://user-images.githubusercontent.com/962850/83576221-887b8b80-a531-11ea-976c-6afbe469200f.png)

**Comment by dtolnay** [comment] 2020-06-02 22:44
I will lock this issue for now because this isn't the place to debug that particular emacs bug.
