### ISSUE TITLE
skip attribute doesn't work in tuple struct

### ISSUE THREAD

**Issue by yshui** [serde-rs/serde#2139] opened 2021-12-10 16:35 UTC
```rust
use serde::{Serialize, Deserialize};

mod cssparser {
    #[derive(Default)]
    pub struct Color;
}

#[derive(Serialize, Deserialize)]
pub struct CSSColor(#[serde(skip)] pub cssparser::Color);

fn main() {}
```

https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=3a73a0bf1d9ea9ec7051efc415fa909b

error:

```
error[E0277]: the trait bound `Color: Serialize` is not satisfied
   --> src/main.rs:9:21
    |
9   | pub struct CSSColor(#[serde(skip)] pub cssparser::Color);
    |                     ^ the trait `Serialize` is not implemented for `Color`
    |
note: required by `serialize_newtype_struct`
   --> /playground/.cargo/registry/src/github.com-1ecc6299db9ec823/serde-1.0.131/src/ser/mod.rs:898:5
    |
898 | /     fn serialize_newtype_struct<T: ?Sized>(
899 | |         self,
900 | |         name: &'static str,
901 | |         value: &T,
902 | |     ) -> Result<Self::Ok, Self::Error>
903 | |     where
904 | |         T: Serialize;
    | |_____________________^

error[E0277]: the trait bound `Color: Deserialize<'_>` is not satisfied
   --> src/main.rs:9:21
    |
9   | pub struct CSSColor(#[serde(skip)] pub cssparser::Color);
    |                     ^ the trait `Deserialize<'_>` is not implemented for `Color`
    |
note: required by a bound in `_::_serde::Deserialize::deserialize`
   --> /playground/.cargo/registry/src/github.com-1ecc6299db9ec823/serde-1.0.131/src/de/mod.rs:539:12
    |
539 |         D: Deserializer<'de>;
    |            ^^^^^^^^^^^^^^^^^ required by this bound in `_::_serde::Deserialize::deserialize`

For more information about this error, try `rustc --explain E0277`.
error: could not compile `playground` due to 2 previous errors

```

**Comment by dtolnay** [comment] 2022-01-23 00:40
Closing as a duplicate of #2105.

**Closed by dtolnay** 2022-01-23 00:40 UTC
