### ISSUE TITLE
Optional different implementation of flatten

### ISSUE THREAD

**Issue by Ploppz** [serde-rs/serde#1801] opened 2020-05-07 08:05 UTC
https://github.com/servo/bincode/issues/245
https://github.com/facebookincubator/serde-reflection/issues/8

This suggestion is one of perhaps many ways to solve the above issues.
In both these cases, it's problematic the way `flatten` is implemented. The implementation works well for self-describing formats of course. But in the cases where one wants to use either of these two crates for example, maybe it should be possible to flatten in a different way? That is, implemented in serde in a way that supports deserializers/serializers like these. Is it possible?

Either a new field attribute like `#[serde(inline)]`, or an item attribute to modulate the implementation of all `flatten`?

**Comment by Mingun** [comment] 2020-09-26 09:21
I think, that new attribute is unnecessary. `serde(flatten)` cause so many weird issues, that it's just broken and should be fully reworked. So this is mostly duplicate of #1183

**Comment by dtolnay** [comment] 2022-01-23 05:14
Yeah I don't feel we need an issue to track this outside of #1183. If there are still remaining limitations after that one has been resolved, please open a new more specific issue at that point.

**Closed by dtolnay** 2022-01-23 05:14 UTC
