### ISSUE TITLE
A tricky enum variant situation

### ISSUE THREAD

**Issue by wbrickner** [serde-rs/serde#2068] opened 2021-08-07 03:00 UTC
Hello,

I have JSON conceptually like this:

```json
{
  "state": "loading",
  "percent_remaining": null,
  "ms_remaining": "2000"
}
```

or also 
```json
{
  "state": "loading",
  "percent_remaining": "23.5",
  "ms_remaining": null
}
```

Because `percent_remaining` and `ms_remaining` never co-occur and one is always present (which one depends on how you initiated the request), 

I would love to deserialize this like

```rust
#[derive(Deserialize)]
enum Remaining {
  #[serde(rename = "percent_remaining")]
  Percent(f64),

  #[serde(rename = "ms_remaining")]
  Milliseconds(f64)
}

#[derive(Deserialize)]
#[serde(tag = "state")]
enum LoadingState {
  #[serde(rename = "failed")]
  Failed,

  #[serde(rename = "loading")]
  Loading {
    #[serde(flatten)]
    remaining: Remaining
  },

  #[serde(rename = "complete")]
  Complete
}

#[derive(Deserialize)]
struct MyMessage {
  #[serde(flatten)]
  state: LoadingState
}
```

This is not really required here but in my actual data / codebase it is very valuable to be able to do this.

The above code actually works when only one of those fields is present, however I have a problem.

The data I have to use does this annoying thing where both `percent_remaining` and `ms_remaining` are always *present* on the object, but one is always `null`, which I would like `serde` to ignore as it is not the `f64` type I declared as a valid deserialization.

What ends up happening is `serde` gets confused (well, it's doing exactly what I've told it, just not what I want).
If one field is `null` (replace Decimal here with f64, my codebase can't use floats):

```
Error("invalid type: null, expected a Decimal type representing a fixed-point number", line: 33, column: 5)'
```

and if neither are null it also fails to deserialize the structure:

```
Error("no variant of enum LoadingState found in flattened data", line: 33, column: 5)
```

I am hoping to get some advice / information on how I can accomplish this to improve the ergonomics / make the user-accessible data idiomatic to Rust (e.g. pretty and impossible to construct / represent an invalid message).

**Comment by jonasbb** [comment] 2021-08-07 13:19
I got a version to compile by changing the definition of `Remaining` to

```rust
#[derive(Serialize, Deserialize, Debug)]
#[serde(untagged)]
enum Remaining {
  Percent{
      percent_remaining: f64,
  },
  Milliseconds {
      ms_remaining: f64,
  }
}
```

I think the problem might be, that the `Remaining` enum, like you defined it, requires a map with a single key. I get as error `invalid value: map, expected map with a single key` when directly deserializing into `Remaining`.

Another problem is that your sample JSON uses strings instead of floats, so you need to tell serde so convert them to f64 during deserialization. You can use [`DisplayFromStr`](https://docs.rs/serde_with/1.9.4/serde_with/struct.DisplayFromStr.html) or [`display_fromstr`](https://docs.rs/serde_with/1.9.4/serde_with/rust/display_fromstr/index.html) from that crate

**Comment by wbrickner** [comment] 2021-08-07 13:29
The core problem I'm facing is the appearance of both keys in the JSON object, the example was more pseudocode.

I'm more looking for help figuring out how to accomplish what I need with serde annotations etc

**Comment by jonasbb** [comment] 2021-08-07 14:00
You can use the definition of `Remaining` which I posted above. In case you do not want to change it or cannot change it, you can also slap `from` and `into` serde attributes on your current definition. [It does work](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=949e5116644561cdb60833d31d3117c2), but cannot run on the playground.

**Comment by omid** [comment] 2021-09-29 16:00
seems like a duplicate of https://github.com/serde-rs/serde/issues/1560

**Closed** 2022-01-23 02:28 UTC
