### ISSUE TITLE
`lowercase`, `snake_case` and `PascalCase` don't work!

### ISSUE THREAD

**Issue by omid** [serde-rs/serde#2635] opened 2023-10-24 12:19 UTC
It's a bit weird that this bug exists or there were some discussions about it.

As you can see in [the source code](https://github.com/serde-rs/serde/blob/master/serde_derive/src/internals/case.rs#L84), `lowercase` and `snake_case` do nothing for structs, since they assume fields are always lowercase already. And [with the same logic](https://github.com/serde-rs/serde/blob/master/serde_derive/src/internals/case.rs#L59) `PascalCase` doesn't work for structs.

Here is [a testing case](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=26ee5a5e6bce08b5dca0bd657003aead).

**Comment by dtolnay** [comment] 2023-10-24 14:53
The other rename rules do not work either in that situation; all of these assume that the Rust name of the type or field conform with Rust convention. This is the intended behavior. Inferring word boundaries from names written in arbitrary case is out of scope for serde_derive.

**Closed by dtolnay** 2023-10-24 14:53 UTC
