### ISSUE TITLE
Implement Serialize for [T; L]

### ISSUE THREAD

**Issue by DasLixou** [serde-rs/serde#2518] opened 2023-07-21 16:07 UTC
implement `Serialize` for a x-long array.
something like `impl<T: Serialize, const L: usize> Serialize for [T; L] { .. }`
with that its possible to do:
```rust
#[derive(Serialize)]
pub struct MyStruct<const R: usize> {
    pub rows: [PosSpan; R],
}
```

**Comment by Max-Meldrum** [comment] 2023-08-19 17:43
See https://github.com/est31/serde-big-array

**Comment by uuhan** [comment] 2024-01-23 08:50
> See https://github.com/est31/serde-big-array

If serde is used in [bindgen](https://github.com/rust-lang/rust-bindgen), it is not easy to add serde-big-array to long array field.

**Comment by hrxi** [comment] 2024-01-27 19:58
Looks like a duplicate of #1937.

**Closed** 2024-01-30 12:18 UTC
