### ISSUE TITLE
Duplicated values when flattening an enum.

### ISSUE THREAD

**Issue by morr0ne** [serde-rs/serde#2234] opened 2022-06-25 01:01 UTC
When flattening an enum the values aren't discared and they get deserialized twice.
Here is a reproducible example:
```rust
use serde::Deserialize;
use serde_json::Value;

#[derive(Debug, Deserialize)]
struct Parsed {
    name: String,
    #[serde(flatten)]
    status: Status,
    #[serde(flatten)]
    unknown: Value,
}

#[derive(Debug, Deserialize)]
#[serde(untagged)]
pub enum Status {
    Dead { hour: u32 },
    Alive { age: u32, residence: String },
}

fn main() {
    let json = r#"{
        "name": "Ben",
        "age": 10,
        "residence": "Planet Earth"
    }"#;

    let parsed: Parsed = serde_json::from_str(json).unwrap();

    println!("{parsed:#?}")
}
```
[link to playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=112f0b487ec33893d25097ba563a45c2)

This outputs the following:
```bash
Parsed {
    name: "Ben",
    status: Alive {
        age: 10,
        residence: "Planet Earth",
    },
    unknown: Object({
        "age": Number(
            10,
        ),
        "residence": String(
            "Planet Earth",
        ),
    }),
}
```

The enum values get parsed both in the status field and the unknown field.
The same thing doesn't happen when using a struct:
```rust
use serde::Deserialize;
use serde_json::Value;

#[derive(Debug, Deserialize)]
struct Parsed {
    name: String,
    #[serde(flatten)]
    status: Status,
    #[serde(flatten)]
    unknown: Value,
}

#[derive(Debug, Deserialize)]
pub struct Status {
    age: u32,
    residence: String,
}

fn main() {
    let json = r#"{
        "name": "Ben",
        "age": 10,
        "residence": "Planet Earth"
    }"#;

    let parsed: Parsed = serde_json::from_str(json).unwrap();

    println!("{parsed:#?}")
}
```
[link to playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=f85f6d5da0183bc204237de95eb22ad7)
Which outputs the following:
```bash
Parsed {
    name: "Ben",
    status: Status {
        age: 10,
        residence: "Planet Earth",
    },
    unknown: Object({}),
}
```
I'd expect the `unknown` field to be an empty object in both cases.
This is clearly a bug as extra data is being parsed which clearly should not have been.

This bug is clearly caused by the way the derive attributes generate deserializing logic.
It also happens on other formats (I actually encoutered this problem while implementing my own format), I chose serde_json to make the examples more readable.

**Comment by morr0ne** [comment] 2022-06-25 01:03
I think this is the same issue highlighted in #2200, I didn't notice at first because of the weird wording in the title.

**Comment by kangalioo** [comment] 2022-10-31 20:32
Yes, this seems to be a duplicate of #2200

**Comment by Mingun** [comment] 2023-05-09 10:15
Even more: this is duplicate of #1909

**Closed** 2023-05-09 10:18 UTC
