### ISSUE TITLE
Deserializing structs with flatten gives very misleading error messages

### ISSUE THREAD

**Issue by Adrodoc** [serde-rs/serde#2035] opened 2021-06-02 19:11 UTC
When using flatten, the fields of the flattened struct are buffered internally, but without line/column information. When such a field is invalid (has the wrong datatype or is unknown when using `deny_unknown_fields`) the line/column information of the end of the serialized struct is used (`}` when using JSON) which can be be very missleading. On top of this the error message does not contain the name of the field, making it very hard to find the faulty field .

As an example the following code gives the error ``Error("invalid type: integer `1`, expected a boolean", line: 4, column: 29)``, but the faulty field `my_bool` is at line 3 in column 19.

cargo.toml:
```toml
serde = { version = "1.0.126", features = ["derive"] }
serde_json = "1.0.64"
```

main.rs:
```rust
use serde::Deserialize;

#[derive(Deserialize)]
struct A {
    my_string: String,
    #[serde(flatten)]
    b: B,
}

#[derive(Deserialize)]
struct B {
    my_bool: bool,
}

fn main() {
    let json = r#"
    {"my_string":"abc",
        "my_bool":1,
        "my_unknown_field":1}
    "#;
    serde_json::from_str::<A>(json).unwrap();
}
```

**Comment by hoon-prestolabs** [comment] 2022-04-12 19:36
I see similar situation with YAML container but, in my case, `serde` reports outer-most node of where the error happens instead of the deepest one.

It would be nice if I can get nested error information.

**Comment by oxalica** [comment] 2022-12-04 13:46
This makes debugging very hard. Is there any workaround?
Here's my usage. It's not always able to inline `Inner` since it's used somewhere else.
```rust
#[derive(Debug, Clone, PartialEq, Eq, Deserialize)]
pub struct Root {
    // Some fields...
    #[serde(flatten)]
    pub inner: Inner,
}

#[derive(Debug, Clone, PartialEq, Eq, Deserialize)]
pub struct Inner {
    // More fields...
}
```
Every errors inside `Inner` are reported at the end of file (end of `Root`).

**Comment by dtolnay** [comment] 2023-07-09 20:10
Line/column-numbering is format-specific functionality, so I think this ends up being a duplicate of #1183.

**Closed by dtolnay** 2023-07-09 20:10 UTC
