### ISSUE TITLE
serde_codegen missing some carraige returns

### ISSUE THREAD

**Issue by mikedilger** [serde-rs/serde#196] opened 2015-12-20 23:45 UTC
This:
```rust
/// An uploaded file that was received as part of `multipart/form-data` parsing.
///
/// Files are streamed to disk because they may not fit in memory.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct UploadedFile {
    /// The temporary file where the data was saved.
    pub path: PathBuf,
    /// The filename that was specified in the data, unfiltered. It may or may not be legal on the
    /// local filesystem.
    pub filename: Option<String>,
    /// The unvalidated content-type that was specified in the data.
    pub content_type: Mime,
    /// The size of the file.
    pub size: usize,
    // The temporary directory the upload was put into, saved for the Drop trait
    tempdir: PathBuf,
}
```
is turning into this:
```rust
/// An uploaded file that was received as part of `multipart/form-data` parsing.////// Files are streamed to disk because they may not fit in memory.#[derive_Clone]
#[derive_PartialEq]
#[derive_Debug]
pub struct UploadedFile {
    /// The temporary file where the data was saved.
    pub path: PathBuf,
    /// The filename that was specified in the data, unfiltered. It may or may not be legal on the
    /// local filesystem.
    pub filename: Option<String>,
    /// The unvalidated content-type that was specified in the data.
    pub content_type: Mime,
    /// The size of the file.
    pub size: usize,
    tempdir: PathBuf,
}
impl ::serde::de::Deserialize for UploadedFile {
...
```
Causing one of the derives to be commented out.
(serde_codegen 0.6.6, syntex 0.22.0)

Any sort of workaround would be appreciated.

**Comment by mtdowling** [comment] 2016-01-06 07:43
Just ran into this today myself. Is this an issue in serde_codegen or in syntex?

**Comment by erickt** [comment] 2016-01-18 17:52
@mtdowling: I think this was supposed to be fixed in the latest syntex and serde_codegen. Which version are you on?

**Comment by jimmycuadra** [comment] 2016-01-23 09:46
This is happening to me using these versions:

* serde_codegen 0.6.10
* syntex 0.26.0

Anyone have a workaround for this in the interim?

**Comment by erickt** [comment] 2016-02-16 16:52
Ugh, I was able to reproduce this. One workaround would be to use the `/** ... */` style comments, as in:

```rust
/**
An uploaded file that was received as part of `multipart/form-data` parsing.

Files are streamed to disk because they may not fit in memory.
*/
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct UploadedFile {
    /// The temporary file where the data was saved.
    pub path: PathBuf,
    /// The filename that was specified in the data, unfiltered. It may or may not be legal on the
    /// local filesystem.
    pub filename: Option<String>,
    /// The unvalidated content-type that was specified in the data.
    pub content_type: Mime,
    /// The size of the file.
    pub size: usize,
    // The temporary directory the upload was put into, saved for the Drop trait
    tempdir: PathBuf,
}
```
That still has the missing-newline, but it won't comment out critical code.

**Comment by erickt** [comment] 2016-02-17 04:11
Turns out this is a rust [pretty printing bug](https://github.com/rust-lang/rust/issues/31722) that syntex inherited.

**Comment by erickt** [comment] 2016-02-17 17:56
Moving this bug over to serde-rs/syntex#31.

**Closed by erickt** 2016-02-17 17:56 UTC
Labels: bug
