### ISSUE TITLE
Easier way to declare default values

### ISSUE THREAD

**Issue by SirWindfield** [serde-rs/serde#1814] opened 2020-05-17 17:47 UTC
I have a struct with a lot of fields (~ 50-ish). The types are mostly a number, a string or a bool. Is there an easier way to declare the default values then using the `default` attribute? E.g.:

```rust
pub struct Config {
    #[serde(default = "default_some_field")]
    some_field: String, // default value is "edged"
}

fn default_some_field() -> String {
    "edged".into()
}
```

I expected the argument to be the default value, e.g. `default = "edged"` where the `proc_macro` tries to `into()` into the type of the field. Maybe the current behaviour could be encoded behind a field called `default_fn` or something. 

P.S.: I am not actually sure if the above proposal is currently possible in `syn`. 

Further examples:

```rust
pub struct Config {
    #[serde(default = "4")]
    int_field: i32,
    #[serde(default = "true")]
    bool_field: bool,
}
```

Would all work as expected as the values can properly be converted using `into()` or `parse`. 

```rust
pub struct Config {
    #[serde(default = "seven")]
    int_field: i32,
}
```

Wouldn't work as `seven` can't be parsed correctly into a number.

**Comment by dtolnay** [comment] 2020-07-05 04:22
Closing as a duplicate of #368.

**Closed by dtolnay** 2020-07-05 04:22 UTC
